/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Livro;
import data.LivroDao;
import data.Conexao;

import java.sql.Connection;
import java.time.LocalDate;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;


public class PainelLivros extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private Connection conexao;
    
    /**
     * Creates new form PainelLivros
     */
    public PainelLivros() {
        initComponents();
        inicializarTabela();
        carregarLivro();
    }
    
    
    //Configurar Tabela
    private void inicializarTabela(){
        tableModel = new DefaultTableModel(
            new Object[]{"ID","Título", "Autor", "Gênero", "Quantidade", "Preço"},
            0
        ){
            @Override
            public boolean isCellEditable (int row, int column){
                return false;
            }    
        };
        
        tblLivros.setModel(tableModel);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        btnNovo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(583, 484));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("LIVROS");

        jLabel2.setText("Buscar");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(31, 58, 95));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(31, 58, 95));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(31, 58, 95));
        btnNovo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TÍTULO", "AUTOR", "GÊNERO", "QUANTIDADE", "PREÇO"
            }
        ));
        jScrollPane1.setViewportView(tblLivros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir)
                        .addComponent(btnEditar)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String texto = txtBuscar.getText();
        
        LivroDao livroDao = new LivroDao();
        Conexao.conectar();

        List<Livro> lista = livroDao.buscarLivro(texto);

        DefaultTableModel modelo = (DefaultTableModel) tblLivros.getModel();
        modelo.setRowCount(0); // limpa tabela

        for (Livro livro : lista) {
            modelo.addRow(new Object[]{
                livro.getIdLivro(),
                livro.getTitulo(),
                livro.getAutor(),
                livro.getGenero(),
                livro.getDataPublicacao(),
                livro.getQuantidade(),
                livro.getPreco(),
                livro.getObservacao()
            });
        }

        Conexao.desconectar(conexao);
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaCadastroLivro tela = new TelaCadastroLivro(this);
        tela.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblLivros.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Selecione um livro para editar",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int id = (int) tblLivros.getValueAt(linha, 0);
        
        LivroDao dao =new LivroDao();
        Livro livro = dao.buscarLivroPorId(id);
        if(livro == null){
            
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados do livro.");
            return;
        };
        

        TelaCadastroLivro tela = new TelaCadastroLivro(this);
        
        tela.setDadosLivro(
            livro.getIdLivro(),
            livro.getTitulo(),
            livro.getAutor(),
            livro.getGenero(),
            livro.getDataPublicacao(),
            livro.getQuantidade(),
            livro.getPreco(),
            livro.getObservacao()
        );
        
        tela.setVisible(true);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tblLivros.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Selecione um livro para excluir",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idLivro = (int) tblLivros.getValueAt(linhaSelecionada, 0);

        int opcao = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir este livro?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
        );

        if (opcao == JOptionPane.YES_OPTION) {

            LivroDao livroDao = new LivroDao();
            livroDao.excluirLivro(idLivro);
            
            JOptionPane.showMessageDialog(this, "Livro excluído com sucesso!");
            carregarLivro(); // atualiza tabela
             
        } else {
            
            JOptionPane.showMessageDialog(this, "Erro ao excluir livro!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    //Carregar tabela
    public void carregarLivro(){
        DefaultTableModel modelo = (DefaultTableModel) tblLivros.getModel();
        modelo.setRowCount(0);
        
        LivroDao livroDao = new LivroDao();
        Connection conexao = Conexao.conectar();
        
        List<Livro> lista = livroDao.listarLivros();

        for (Livro livro : lista) {
            tableModel.addRow(new Object[]{
                livro.getIdLivro(),
                livro.getTitulo(),
                livro.getAutor(),
                livro.getGenero(),
                livro.getQuantidade(),
                livro.getPreco(),
            });
        }
        
        Conexao.desconectar(conexao);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
