/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import data.Conexao;
import data.HistoricoDao;
import java.sql.Connection;
import model.Historico;
import model.Funcionario;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sidne
 */
public class PainelHistorico extends javax.swing.JPanel {

    private List<Historico> historico;
    private DefaultTableModel tableModel;
    private Connection conexao;
    
    /**
     * Creates new form PainelHistorico
     */
    public PainelHistorico() {
        initComponents();
        historico = new ArrayList<>();
        inicializarTabela();
        inicializarDadosTeste();
        carregarHistorico();
    }

    //Configurar Tabela
    private void inicializarTabela(){
        tableModel = new DefaultTableModel(
            new Object[]{"ID","TipoAcao", "Entidade", "IdRegistro", "Funcionario", "DataHora"},
            0
        ){
            @Override
            public boolean isCellEditable (int row, int column){
                return false;
            }    
        };
        
        tblHistorico.setModel(tableModel);
    }
    
    //Dados teste
    private void inicializarDadosTeste() {
        
    // Funcionário
    Funcionario funcionario1 = new Funcionario(
            "Ricardo Silva", 
            "Gerente",
            "GERENTE", 
            "ricardo", 
            "213"
    );

    }
    
    //Carregar tabela
    private void carregarHistorico(){
        DefaultTableModel modelo = (DefaultTableModel) tblHistorico.getModel();
        modelo.setNumRows(0);
        
        HistoricoDao dao = new HistoricoDao();
        
        List<Historico> lista = dao.listarHistorico();

        for (Historico h : lista) {
            modelo.addRow(new Object[]{
                h.getIdHistorico(),
                h.getTipoAcao(),
                h.getTabelaMovimentada(),
                h.getIdRegistroMovimento(),
                h.getFuncionario().getNome(),
                h.getDataHora()
            });
        }
        
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TIPO AÇÃO", "ENTIDADE AFETADA", "ID REGISTRO", "FUNCIÓNARIO", "DATA/HORA"
            }
        ));
        jScrollPane1.setViewportView(tblHistorico);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("HISTÓRICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorico;
    // End of variables declaration//GEN-END:variables
}
